### ISSUE TITLE
Add Craft 4 support

### ISSUE THREAD

**Issue by umkasanki** [Story-Chief/craft-cms-module-storychief#3]
Hi guys!
Could you add Craft 4 support?

**Comment by gregory-claeyssens** [comment]
Hey @umkasanki the repo names are a bit confusing right now, but you can find our Craft4 module [here](https://github.com/Story-Chief/craft-cms-module-storychief-v3/tree/craft-cms-4)

**Comment by umkasanki** [comment]
Ok. Thanks
